services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: always
    ports:
      - "5432:5432"
    secrets:
      - db_password
    volumes:
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
  web:
    image: python:latest
    restart: always
    command: [ "sh", "/web_init.sh" ]
    secrets:
      - db_password
    volumes:
      - ../src:/app/src
      - ../main.py:/app/main.py
      - ../requirements.txt:/app/requirements.txt
      - ../defaults.toml:/app/defaults.toml
      - ./web_init.sh:/web_init.sh
    ports:
      - "8005:8005"
  frontend:
    image: node:21
    ports:
      - "3000:3000"
    volumes:
      - ../frontend/schwotz-frontend:/schwotz-frontend
      - ./frontend_init.sh:/frontend_init.sh
    command: [ "sh", "/frontend_init.sh" ]

secrets:
  db_password:
    file: secret_db_password.toml
