services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: always
    ports:
      - "5432:5432"
    secrets:
      - db_password
    volumes:
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh

secrets:
  db_password:
    file: secret_db_password.toml
